### ISSUE TITLE
SESSION #55 : changement de titre

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#11]
> Tiphanie VINET | Tiphanie VINET | 12:56 (il y a 4 heures) |   |  
>
> Bonjour,
> 
> Suite aux différents échanges, voici le titre définitif:
> Developper sa maturité produit, ce qu'il faut savoir!

**Comment by epatrizio** [comment]
Done !

**Comment by Frederic-ANDRE** [comment]
Attention, fait coté https://github.com/agile-france/site-dessins
Il faut voir si @JeanPierreBONNAFOUS l'a fait ici, dans les versions papiers.

**Comment by JeanPierreBONNAFOUS** [comment]
A faire sur le PDF

**Comment by JeanPierreBONNAFOUS** [comment]
intégré dans la version 1.04 sur le PDF

**Comment by JeanPierreBONNAFOUS** [comment]
Le titre n'est pas à jour dans le Schedule-print.csv impact sur l'affiche ROTI @Frederic-ANDRE

**Comment by Frederic-ANDRE** [comment]
c'est fait dans les CSV et programme.html
https://github.com/agile-france/site-dessins/commit/3b0f8230e4c9050be8aa325c6d744aa8b35fd679?diff=unified

**Comment by Frederic-ANDRE** [comment]
Closed https://github.com/agile-france/site-dessins/issues/25
