### ISSUE TITLE
SESSION #131 à échanger avec #1, #18, #76 et #93

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#13]
Les enfants terribles de l'agilité, l'atelier ludo parodico télévisuo pédagogique ! 

> Pour le programme notre atelier est limité à 30 participants, je vois que vous nous avez réservé l'amphi 300 places c'est surement surdimensionné, pouvez-vous adapter ?

**Comment by JeanPierreBONNAFOUS** [comment]
Et du coup... on le déplace où?

**Comment by JeanPierreBONNAFOUS** [comment]
Le SWAP est fait sur PDF et SVG en version 1.06 jeudi matin

**Comment by Frederic-ANDRE** [comment]
Le swap est fait dans les CSV.
https://github.com/agile-france/site-dessins/issues/27

**Comment by JeanPierreBONNAFOUS** [comment]
fait sur le PDF
