### ISSUE TITLE
SESSION #144 changement de titre Education Nationale

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#15]
Education Nationale : Qui a dit que le mammouth ne pouvait pas être agile ?

**Comment by Frederic-ANDRE** [comment]
Fait :
fichiers CSV + fichier programme.html
https://github.com/agile-france/site-dessins/commit/239609bfad357c953b5427d889c0c6e63b6f1ba4

**Comment by Frederic-ANDRE** [comment]
Closed https://github.com/agile-france/site-dessins/issues/29

**Comment by JeanPierreBONNAFOUS** [comment]
Fait dans PDF
