### ISSUE TITLE
SESSION échanger #112 la vie et #33 devops

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#18]

**Comment by Frederic-ANDRE** [comment]
https://github.com/agile-france/site-dessins/commit/0bb22cb0efe46161ca7d3c4bd333c1d007db434d#diff-4f349f861bc9a42b87cbe82bd5c6cc61

**Comment by JeanPierreBONNAFOUS** [comment]
Fait sur PDF
