### ISSUE TITLE
SESSION #85 L’agilité ça ne marche pas mettre 16h25 - 17h10

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#19]
Pour la session **L’agilité ça ne marche pas ! Ok, mais pourquoi ?**  ils ont besoin de 45 minutes il faut mettre 16h25 - 17h10 sur le PDF

**Comment by JeanPierreBONNAFOUS** [comment]
Fait sur PDF
