### ISSUE TITLE
COQUILLE agenda-AF19-Educathon.pdf -> corriger url et QRcode

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#31]
l'url bit.ly ne mène nulle part et le QRcode non plus

**Comment by Frederic-ANDRE** [comment]
mettre http://prog.conf.agile-france.org + QRcode noir

**Comment by JeanPierreBONNAFOUS** [comment]
Je sais, c'est un FAKE pour la mise en page

**Comment by JeanPierreBONNAFOUS** [comment]
Faire pointer le QR CODE vers
Le programme
 https://docs.google.com/spreadsheets/d/1PDH7QrqTKrwZTyPdw8kh88kb3F-eH4slma02JFi5G2E/edit#gid=0

**Comment by JeanPierreBONNAFOUS** [comment]
URL : http://educathon.conf.agile-france.org/
Manque plus qu'a créer le QRCode

**Comment by JeanPierreBONNAFOUS** [comment]
Fait
