### ISSUE TITLE
SESSION 58 Bullshit Game ajout d'orateurs

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#34]
Emmanuelle LEFORT 
Marina SOSNIAK
Delphine LEGAL
Pascal POUSSARD
Laurent DASSAULT

**Comment by JeanPierreBONNAFOUS** [comment]
ça fait bcp d'Orateur :)
A Faire sur BIG et Affiche ROTI
Pas d'impact sur BADGE PRogramme

**Comment by JeanPierreBONNAFOUS** [comment]
Fix sur AFFICHE ROTI

**Comment by JeanPierreBONNAFOUS** [comment]
Fix sur BIG
