### ISSUE TITLE
SESSION 18 switché mon cerveau : seconde oratrice Suzon BEAUSSANT à ajouter

### ISSUE THREAD

**Issue by Frederic-ANDRE** [JeanPierreBONNAFOUS/AF19PROGRAMME#36]

**Comment by JeanPierreBONNAFOUS** [comment]
@Frederic-ANDRE t'es sur de ça??? 
Le Schedule.csv ne contient que le nom d'Aurélien, le prog en ligne aussi... 
Le Form ROTI est à jour avec les 2 noms.

**Comment by JeanPierreBONNAFOUS** [comment]
Fix sur AFFICHE ROTI

**Comment by JeanPierreBONNAFOUS** [comment]
Fix sur BIG
